services:
  frontend:
    build:
      context: ./frontend
      target: development
    container_name: frontend
    restart: always
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      target: development
    container_name: backend
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=development
    volumes:
      - ./backend:/backend
      - /backend/node_modules
